spring:
  application:
    name: INTERNSHIP
  datasource:
    url: jdbc:postgresql://postgreSQL:5432/myServiceDB
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    virtual-host: vhost
    username: test
    password: test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    instance:
      preferIpAddress: true

server:
  servlet:
    context-path: /api
  port: 8085