spring:
  application:
    name: internship
  datasource:
    url: jdbc:postgresql://internshipDB:5432/myServiceDB
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml

server:
  servlet:
    context-path: /api
  port: 8080