version: "3.9"

services:
  internshipDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: myServiceDB
    ports:
      - "5433:5432"
#    volumes: